name: Publish Package Pipeline

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./adblock-detect-react
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v2.2.3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - run: pnpm build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
